<a href="https://colab.research.google.com/github/ksalung/Behavioral_Pattern/blob/ksalung/numpy_test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
import sys
import numpy as np
x = 6
x

6

In [12]:
x = np.array([1,2,3])
x.shape

(3,)

In [10]:
x = np.array([1])
x.shape

(1,)

In [13]:
np.argmax(x)

2

In [14]:
x.argmax()

2

In [16]:
y = np.array([[1,2,3],[2,3,4],[5,6,7],[8,9,10]])
print(y)

[[ 1  2  3]
 [ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [17]:
y.shape

(4, 3)

In [19]:
print(y[:2,1:])

[[2 3]
 [3 4]]


In [20]:
print(y[2, :])

[5 6 7]


In [21]:
print(y[1:2, :2].shape)

(1, 2)


In [23]:
a = np.array([[2,1],[1,4]])
b = np.array([[1,2,0],[0,1,2]])
print(a)
print()
print(b)
print()
print(np.matmul(a,b))
np.dot(a,b)

[[2 1]
 [1 4]]

[[1 2 0]
 [0 1 2]]

[[2 5 2]
 [1 6 8]]


array([[2, 5, 2],
       [1, 6, 8]])

In [24]:
list(range(8))

[0, 1, 2, 3, 4, 5, 6, 7]

In [28]:
 A = np.arange(9)
 A

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [30]:
b = A.reshape(3,3)
b

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [31]:
b.T

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])